plugins {
    alias(libs.plugins.android.library)
}

android {
    buildToolsVersion "36.1.0"
    namespace "app.lawnchair.compatlib"

    buildFeatures {
        aidl true
    }

    sourceSets {
        main {
            aidl.srcDirs = ['src/main/java']
        }
    }
}

dependencies {
    compileOnly libs.androidx.annotation
}

addFrameworkJar('framework-15.jar')
