name: Release update

on:
  workflow_dispatch:
    inputs:
      artifactName:
        description: Artifact name
        type: string
        required: true
      tagName:
        description: Tag name
        type: string
        required: true
      prerelease:
        description: Prerelease
        type: boolean
        required: true
      releaseName:
        description: Release name
        type: string
        required: true

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v6
        with:
          submodules: true
      - uses: actions/setup-java@3a4f611406f44a9a0f49720d3e193516efd41c7c # v5
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@94baf225fe0a508e58197d90057f109565bb962c # v5
      - name: Write sign info
        id: sign-release-apk
        if: github.repository_owner == 'LawnchairLauncher'
        run: |
          if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
            echo storePassword='${{ secrets.KEYSTORE_PASSWORD }}' >> keystore.properties
            echo keyAlias='${{ secrets.KEY_ALIAS }}' >> keystore.properties
            echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> keystore.properties
            echo storeFile='${{ github.workspace }}/key.jks' >> keystore.properties
            echo ${{ secrets.KEYSTORE }} | base64 --decode > ${{ github.workspace }}/key.jks
          fi
      - name: Build release APK
        run: ./gradlew assembleLawnWithQuickstepGithubRelease
      - name: Rename artifact
        run: mv build/outputs/apk/**/**/*.apk "${{ github.event.inputs.artifactName }}"
      - name: Attest
        uses: actions/attest-build-provenance@96278af4e58a37347b52b3981644f43d3ccffdd2 # v3
        with:
          subject-path: ${{ github.event.inputs.artifactName }}
      - name: Upload artifact
        uses: actions/upload-artifact@b7c566a073f6528939c3588445031d8010d5ad11 # v6
        with:
          name: Release APK
          path: ${{ github.event.inputs.artifactName }}

  publish-github-release:
    runs-on: ubuntu-latest
    needs: build-release-apk
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v6
      - name: Download artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e0059713729680a139 # v4
        with:
          name: Release APK
          path: artifacts/release-apk
      - name: Publish GitHub release
        uses: softprops/action-gh-release@a06a81ae3018251469c0d381d0633d8359fd3a94 # v2
        with:
          tag_name: ${{ github.event.inputs.tagName }}
          prerelease: ${{ github.event.inputs.prerelease }}
          draft: true
          body_path: ${{ github.workspace }}/GITHUB_CHANGELOG.md
          files: artifacts/release-apk/${{ github.event.inputs.artifactName }}
          name: ${{ github.event.inputs.releaseName }}

  publish-telegram-update-post:
    runs-on: ubuntu-latest
    needs: build-release-apk
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v6
      - name: Download artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e0059713729680a139 # v4
        with:
          name: Release APK
          path: artifacts/release-apk
      - uses: actions/setup-python@3975157804581319831b512222f46914d003d44a # v6
        with:
          python-version: 3.x
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install gitpython requests
      - name: Publish Telegram update post
        run: python ci.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_CI_BOT_TOKEN }}
          ARTIFACT_DIRECTORY: artifacts/release-apk
          TELEGRAM_NEWS_CHANNEL_ID: ${{ secrets.TELEGRAM_NEWS_CHANNEL_ID }}
          ACTION: update_announcement
